# Generated by Django 4.2.17 on 2024-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='regis_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
