# Generated by Django 4.2.17 on 2024-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_course_regis_date_alter_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
